In [63]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [64]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path("../Neural-Networks_Mod13/applicants_data.csv"))

# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [65]:
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [66]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN","NAME"])
# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [67]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [68]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [69]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [70]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data,columns = enc.get_feature_names_out(categorical_variables))

# Review the DataFrame
encoded_df

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [71]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_variables_df = applicant_data_df.drop(columns = categorical_variables)

In [72]:
encoded_numerical_df = pd.concat([numerical_variables_df,encoded_df],axis=1)

# Review the Dataframe
encoded_numerical_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [73]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_numerical_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [74]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_numerical_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X[:5]

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [75]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test =  train_test_split(X, y, random_state=1)

In [76]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [77]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [78]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [79]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features+number_output_neurons)//2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [80]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1+number_output_neurons)//2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [81]:
# Create the Sequential model instance
nn = Sequential()

In [82]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1,input_dim=number_input_features,activation="relu"))

In [83]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2,activation="relu"))

In [84]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [85]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_11 (Dense)            (None, 58)                6786

 dense_12 (Dense)            (None, 29)                1711

 dense_13 (Dense)            (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [86]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [87]:
# Fit the model using 50 epochs and the training data
fit_model=nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5787 - accuracy: 0.7196
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5544 - accuracy: 0.7291
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5498 - accuracy: 0.7332
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5482 - accuracy: 0.7312
Epoch 5/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5475 - accuracy: 0.7317
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5455 - accuracy: 0.7329
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5444 - accuracy: 0.7343
Epoch 8/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5441 - accuracy: 0.7331
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5430 - accuracy: 0.7348
Epoch 10/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5420 - accuracy: 0.7350
Epoch 11/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5418 - accuracy: 0.7346
Epoch 12/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5409 - accuracy: 0.7351
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5408 - accuracy: 0.7350
Epoch 14/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5406 - accuracy: 0.7358
Epoch 15/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5395 - accuracy: 0.7369
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7362
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5386 - accuracy: 0.7380
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5384 - accuracy: 0.7368
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5380 - accuracy: 0.7372
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7379
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7375
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5376 - accuracy: 0.7379
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5365 - accuracy: 0.7379
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7383
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5364 - accuracy: 0.7387
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5362 - accuracy: 0.7387
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5355 - accuracy: 0.7383
Epoch 28/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7395
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5357 - accuracy: 0.7392
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5354 - accuracy: 0.7386
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5352 - accuracy: 0.7388
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5352 - accuracy: 0.7391
Epoch 33/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7391
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5348 - accuracy: 0.7390
Epoch 35/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5346 - accuracy: 0.7385
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7403
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5336 - accuracy: 0.7402
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7397
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5340 - accuracy: 0.7407
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5334 - accuracy: 0.7393
Epoch 41/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5333 - accuracy: 0.7407
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5328 - accuracy: 0.7403
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5329 - accuracy: 0.7385
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5326 - accuracy: 0.7404
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5329 - accuracy: 0.7414
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5328 - accuracy: 0.7411
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5325 - accuracy: 0.7412
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5324 - accuracy: 0.7402
Epoch 49/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7410
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5323 - accuracy: 0.7404

In [89]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5540 - accuracy: 0.7310 - 744ms/epoch - 3ms/step
Loss: 0.5540251731872559, Accuracy: 0.7309620976448059

In [90]:
# Set the model's file path
file_path = Path("Neural-Networks_Mod13/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

Alternative Model 1

In [91]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [92]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [93]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features+number_output_neurons)//2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [94]:
# Define the number of hidden nodes for the second hidden layer and display
hidden_nodes_layer2_A1 =  (hidden_nodes_layer1_A1+number_output_neurons)//2
hidden_nodes_layer2_A1

29

In [95]:
# Define the number of hidden nodes for the third hidden layer and display
hidden_nodes_layer3_A1 =  (hidden_nodes_layer2_A1+number_output_neurons)//2
hidden_nodes_layer3_A1

15

In [96]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [97]:
# Add three hidden layers
nn_A1.add(tf.keras.layers.Dense(units=hidden_nodes_layer1_A1,input_dim=number_input_features,activation="relu"))
nn_A1.add(tf.keras.layers.Dense(units=hidden_nodes_layer2_A1,activation="relu"))
nn_A1.add(tf.keras.layers.Dense(units=hidden_nodes_layer3_A1,activation="relu"))

# Output layer
nn_A1.add(tf.keras.layers.Dense(units=number_output_neurons_A1,activation="sigmoid"))

# Check the structure of the model
nn_A1.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_14 (Dense)            (None, 58)                6786

 dense_15 (Dense)            (None, 29)                1711

 dense_16 (Dense)            (None, 15)                450

 dense_17 (Dense)            (None, 1)                 16

=================================================================
Total params: 8,963
Trainable params: 8,963
Non-trainable params: 0
_________________________________________________________________

In [98]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [99]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn.fit(X_train_scaled,y_train,epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5316 - accuracy: 0.7409
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7406
Epoch 3/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5320 - accuracy: 0.7411
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5319 - accuracy: 0.7412
Epoch 5/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5316 - accuracy: 0.7407
Epoch 6/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5316 - accuracy: 0.7415
Epoch 7/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 8/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5314 - accuracy: 0.7410
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5314 - accuracy: 0.7413
Epoch 10/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5308 - accuracy: 0.7413
Epoch 11/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5309 - accuracy: 0.7424
Epoch 12/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5308 - accuracy: 0.7420
Epoch 14/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5306 - accuracy: 0.7426
Epoch 15/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5310 - accuracy: 0.7414
Epoch 16/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5307 - accuracy: 0.7413
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5304 - accuracy: 0.7419
Epoch 18/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7417
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5301 - accuracy: 0.7417
Epoch 20/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5304 - accuracy: 0.7408
Epoch 21/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5303 - accuracy: 0.7427
Epoch 22/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5296 - accuracy: 0.7422
Epoch 23/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5298 - accuracy: 0.7421
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5300 - accuracy: 0.7418
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5294 - accuracy: 0.7424
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5301 - accuracy: 0.7424
Epoch 27/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5295 - accuracy: 0.7425
Epoch 28/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5300 - accuracy: 0.7420
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7426
Epoch 30/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7419
Epoch 31/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5296 - accuracy: 0.7427
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5295 - accuracy: 0.7423
Epoch 33/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5291 - accuracy: 0.7429
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5288 - accuracy: 0.7428
Epoch 35/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7424
Epoch 36/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5289 - accuracy: 0.7428
Epoch 37/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5294 - accuracy: 0.7423
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5291 - accuracy: 0.7417
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5292 - accuracy: 0.7421
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5293 - accuracy: 0.7417
Epoch 41/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5287 - accuracy: 0.7420
Epoch 42/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5288 - accuracy: 0.7427
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5287 - accuracy: 0.7427
Epoch 44/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5284 - accuracy: 0.7423
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5288 - accuracy: 0.7429
Epoch 46/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5287 - accuracy: 0.7429
Epoch 47/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5286 - accuracy: 0.7424
Epoch 48/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5284 - accuracy: 0.7432
Epoch 49/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5286 - accuracy: 0.7422
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5285 - accuracy: 0.7424

Alternative Model 2

In [100]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [101]:
# Define the number of neurons in the output layer
number_output_neurons_A2 =1

In [102]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = round(number_input_features*0.6666)

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

77

In [103]:
#Second hidden layer
hidden_nodes_layer2_A2=(hidden_nodes_layer1_A2+number_output_neurons_A2)//2
hidden_nodes_layer2_A2

39

In [104]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [105]:
# add hidden layers
nn_A2.add(tf.keras.layers.Dense(units=hidden_nodes_layer1_A2,input_dim=number_input_features,activation="relu"))
nn_A2.add(tf.keras.layers.Dense(units=hidden_nodes_layer2_A2,activation="relu"))

# Output layer
nn_A2.add(tf.keras.layers.Dense(units=number_output_neurons_A2,activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_18 (Dense)            (None, 77)                9009

 dense_19 (Dense)            (None, 39)                3042

 dense_20 (Dense)            (None, 1)                 40

=================================================================
Total params: 12,091
Trainable params: 12,091
Non-trainable params: 0
_________________________________________________________________

In [106]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [107]:
# Fit the model
fit_model_A2 = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5284 - accuracy: 0.7430
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5281 - accuracy: 0.7428
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5282 - accuracy: 0.7428
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5278 - accuracy: 0.7427
Epoch 5/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5279 - accuracy: 0.7431
Epoch 6/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5277 - accuracy: 0.7427
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5281 - accuracy: 0.7424
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5279 - accuracy: 0.7434
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5282 - accuracy: 0.7431
Epoch 10/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5279 - accuracy: 0.7423
Epoch 11/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5276 - accuracy: 0.7428
Epoch 12/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5285 - accuracy: 0.7425
Epoch 13/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5276 - accuracy: 0.7432
Epoch 14/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5277 - accuracy: 0.7427
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5283 - accuracy: 0.7426
Epoch 16/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5275 - accuracy: 0.7430
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5278 - accuracy: 0.7425
Epoch 18/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5277 - accuracy: 0.7428
Epoch 19/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5274 - accuracy: 0.7434
Epoch 20/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5274 - accuracy: 0.7432
Epoch 21/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5274 - accuracy: 0.7428
Epoch 22/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5275 - accuracy: 0.7432
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5274 - accuracy: 0.7425
Epoch 24/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5270 - accuracy: 0.7429
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5269 - accuracy: 0.7428
Epoch 26/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5272 - accuracy: 0.7437
Epoch 27/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5275 - accuracy: 0.7432
Epoch 28/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5270 - accuracy: 0.7429
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5269 - accuracy: 0.7428
Epoch 30/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5273 - accuracy: 0.7432
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5269 - accuracy: 0.7430
Epoch 32/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5273 - accuracy: 0.7432
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5277 - accuracy: 0.7429
Epoch 34/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5274 - accuracy: 0.7433
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5267 - accuracy: 0.7440
Epoch 36/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5272 - accuracy: 0.7431
Epoch 37/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5270 - accuracy: 0.7429
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5266 - accuracy: 0.7437
Epoch 39/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5272 - accuracy: 0.7432
Epoch 40/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5267 - accuracy: 0.7435
Epoch 41/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5265 - accuracy: 0.7436
Epoch 42/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5269 - accuracy: 0.7431
Epoch 43/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5266 - accuracy: 0.7432
Epoch 44/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5271 - accuracy: 0.7429
Epoch 45/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5271 - accuracy: 0.7432
Epoch 46/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5266 - accuracy: 0.7440
Epoch 47/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5258 - accuracy: 0.7443
Epoch 48/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5264 - accuracy: 0.7429
Epoch 49/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5262 - accuracy: 0.7432
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5266 - accuracy: 0.7427
Epoch 51/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5266 - accuracy: 0.7430
Epoch 52/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5262 - accuracy: 0.7433
Epoch 53/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5265 - accuracy: 0.7429
Epoch 54/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5262 - accuracy: 0.7432
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5266 - accuracy: 0.7440
Epoch 56/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5262 - accuracy: 0.7442
Epoch 57/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5262 - accuracy: 0.7436
Epoch 58/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5260 - accuracy: 0.7436
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5261 - accuracy: 0.7435
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5268 - accuracy: 0.7434
Epoch 61/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5269 - accuracy: 0.7437
Epoch 62/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5260 - accuracy: 0.7431
Epoch 63/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5259 - accuracy: 0.7429
Epoch 64/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5260 - accuracy: 0.7429
Epoch 65/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5259 - accuracy: 0.7436
Epoch 66/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5258 - accuracy: 0.7444
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5268 - accuracy: 0.7430
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5260 - accuracy: 0.7428
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5262 - accuracy: 0.7435
Epoch 70/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5263 - accuracy: 0.7432
Epoch 71/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5261 - accuracy: 0.7441
Epoch 72/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5262 - accuracy: 0.7437
Epoch 73/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5258 - accuracy: 0.7438
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5258 - accuracy: 0.7437
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5259 - accuracy: 0.7441
Epoch 76/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5260 - accuracy: 0.7434
Epoch 77/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5258 - accuracy: 0.7441
Epoch 78/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5256 - accuracy: 0.7432
Epoch 79/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5260 - accuracy: 0.7435
Epoch 80/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5256 - accuracy: 0.7436
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5257 - accuracy: 0.7428
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5258 - accuracy: 0.7442
Epoch 83/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5257 - accuracy: 0.7436
Epoch 84/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5256 - accuracy: 0.7437
Epoch 85/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5258 - accuracy: 0.7430
Epoch 86/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5253 - accuracy: 0.7436
Epoch 87/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5257 - accuracy: 0.7433
Epoch 88/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5258 - accuracy: 0.7433
Epoch 89/100
804/804 [==============================] - 1121s 1s/step - loss: 0.5259 - accuracy: 0.7440
Epoch 90/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5258 - accuracy: 0.7440
Epoch 91/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5259 - accuracy: 0.7443
Epoch 92/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5252 - accuracy: 0.7436
Epoch 93/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5255 - accuracy: 0.7439
Epoch 94/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5254 - accuracy: 0.7433
Epoch 95/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5256 - accuracy: 0.7437
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5254 - accuracy: 0.7432
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5253 - accuracy: 0.7435
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5256 - accuracy: 0.7434
Epoch 99/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5251 - accuracy: 0.7440
Epoch 100/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5255 - accuracy: 0.7436

In [114]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 1s - loss: 0.5664 - accuracy: 0.7298 - 823ms/epoch - 3ms/step
Loss: 0.5663544535636902, Accuracy: 0.7297959327697754

In [115]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.6956 - accuracy: 0.4897 - 757ms/epoch - 3ms/step
Loss: 0.6955849528312683, Accuracy: 0.4896793067455292

In [116]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.7479 - accuracy: 0.4869 - 730ms/epoch - 3ms/step
Loss: 0.7479112148284912, Accuracy: 0.48688048124313354

In [118]:
# Set the file path for the first alternative model
file_path = Path("Neural-Networks_Mod13/AlphabetSoup_A1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [119]:
# Set the file path for the second alternative model
file_path = Path("Neural-Networks_Mod13/AlphabetSoup_A2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)